---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      gtk_ver: v0.0.4
  tasks:
    - command: /usr/local/bin/gitops-toolkit
      register: gtk_test_output
    - name: assert binary prints help output
      debug:
        msg: '{{ gtk_test_output.stdout }}'

