---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      gtk_ver: v0.0.4
      # generally the following does not need to be set
      gtk_argocd:
        namespace: override-namespace
        manifest:
          dir: "/tmp/argocd_manifest" # required override as it will take the user name ie root/username
          git:
            enabled: false # disable - builder image does not have git installed - oops!
  tasks:
    - name: assert binaries are runnable
      command: "{{ item }}"
      register: exec
      failed_when: exec.rc > 0
      loop:
        - /usr/local/bin/gitops-toolkit
        - /usr/local/bin/kubectl
        - /usr/local/bin/argocd

    - name: Get Home clusters yaml stat
      stat:
        path : "{{ ansible_env.HOME }}/.gitops-toolkit-clusters.yaml"
      register: home_clusters_yaml

    - name: Get Home clusters yaml checksum
      set_fact:
        home_clusters_sha: "{{ home_clusters_yaml.stat.checksum }}"

    - name: Get Expected clusters yaml stat
      stat:
        path : "./tests/expected.clusters.yaml"
      register: expected_clusters_yaml

    - name: Get Expected clusters yaml checksum
      set_fact:
        expected_clusters_sha: "{{ expected_clusters_yaml.stat.checksum }}"
      failed_when:  expected_clusters_sha != home_clusters_sha