---
# tasks file for gitops-toolkit
- set_fact:
    _gtk_argocd: "{{ gtk_argocd_defaults | combine(gtk_argocd, recursive=True) }}"
- include_tasks: install_gtk.yml
- include_tasks: install_cacert.yml

- name: install argocd deploy manifest - {{ _gtk_argocd.manifest.git.repo }}@{{ _gtk_argocd.manifest.git.version }}
  when: _gtk_argocd.manifest.git.enabled
  git:
    repo: "{{ _gtk_argocd.manifest.git.repo }}"
    version: "{{ _gtk_argocd.manifest.git.version }}"
    dest: "{{ _gtk_argocd.manifest.dir }}"

- name: configuring {{ ansible_env.HOME }}/.gitops-toolkit-clusters.yaml
  become: true
  become_user: root
  template:
    src: '{{ gtk_cluster_template_yaml }}'
    dest: '{{ ansible_env.HOME }}/.gitops-toolkit-clusters.yaml'
    mode: '{{ item.m | default("0644") }}'
