---
- name: andrewrothstein.unarchivedeps
  version: 3.0.1
- name: andrewrothstein.kubectl
  version: v1.3.4
- name: andrewrothstein.argocd
  version: v1.2.25
- name: bradfordwagner.go-releaser-install
  version: 1.2.0
